// demo/demo-vue3/src/Stories.vue
<template>
  <stories-app :modules.prop="modules" @storyChange="storySelected" @storyContextChange="contextSelected">
    <stories-split-pane split="horizontal" min-size="150" default-size="250">
      <stories-sidebar slot="slot1"></stories-sidebar>
      <div slot="slot2">
        <stories-tool-bar>
          <stories-tool-zoom slot="left"></stories-tool-zoom>
        </stories-tool-bar>
        <stories-split-pane split="vertical" min-size="250" default-size="500">
          <stories-preview slot="slot1">
            <story-vue-renderer :story="story"></story-vue-renderer>
          </stories-preview>
          <stories-tabs slot="slot2">
            <stories-tab-bar>
              <stories-tab-button tab="actions">
                <stories-label color="primary">Actions</stories-label>
              </stories-tab-button>
              <stories-tab-button tab="controls">
                <stories-label color="primary">Controls</stories-label>
              </stories-tab-button>
            </stories-tab-bar>
            <stories-tab tab="actions">
              <stories-addon-actions></stories-addon-actions>
            </stories-tab>
            <stories-tab tab="controls">
              <stories-addon-controls></stories-addon-controls>
            </stories-tab>
          </stories-tabs>
        </stories-split-pane>
      </div>
    </stories-split-pane>
  </stories-app>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { StoryComponent, StoryContext } from "@stories-js/stories-components";

import { StoryVueRenderer } from "@stories-js/stories-vue3";

import storyModules from "./stories-list";


export default defineComponent({
  name: "Stories",
  components: {
    StoryVueRenderer,
  },
  data() {
    return {
      modules: storyModules,
      story: null as StoryComponent | null,
      context: null as StoryContext | null,
    };
  },
  methods: {
    storySelected(event: CustomEvent<StoryComponent>) {
      console.log("!!! storySelected", event.detail);
      this.story = event.detail;
    },
    contextSelected(event: CustomEvent<StoryContext>) {
      console.log("contextSelected", event.detail);
      this.context = event.detail;
    }
  },
});
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  /* text-align: center; */
  color: #2c3e50;
  margin-top: 0px;
}
</style>

// demo/demo-angular/src/stories/stories.component.ts
import type { OnInit } from '@angular/core';
import { HostListener } from '@angular/core';
import { Component } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { StoriesAngularService } from '@stories-js/stories-angular';
import type { StoryComponent } from '@stories-js/stories-angular';
import type { StoryContext, StoryModules } from '@stories-js/stories-components';

@Component({
  selector: 'app-root',
  templateUrl: './stories.component.html',
  styleUrls: ['./stories.component.css']
})
export class StoriesComponent implements OnInit {
  modules: StoryModules = [];
  story: StoryComponent | undefined;
  context: StoryContext | undefined;

  constructor(private service: StoriesAngularService) {}

  ngOnInit(): void {
      this.modules = this.service.modules;
      console.log('StoriesComponent.modules', this.modules);
  }

  @HostListener('storyChange', ['$event.detail'])
  setStory(story: StoryComponent): void {
    console.log('StoriesComponent.setStory', story);
    this.story = story;
  }

  @HostListener('storyContextChange', ['$event.detail'])
  setContext(context: StoryContext): void {
    console.log('StoriesComponent.setContext', context);
    this.context = context;
  }
}

<stories-app [modules]="modules" (storyChange)="setStory" (storyContextChange)="setContext">
  <stories-split-pane split="horizontal" minSize="150" defaultSize="250">
    <stories-sidebar slot="slot1"></stories-sidebar>
    <div slot="slot2">
      <stories-tool-bar>
        <stories-tool-zoom slot="left"></stories-tool-zoom>
      </stories-tool-bar>
      <stories-split-pane split="vertical"  minSize="250" defaultSize="500">
        <stories-preview slot="slot1">
          <stories-angular-renderer [story]="story"></stories-angular-renderer>
        </stories-preview>
        <stories-tabs slot="slot2">
          <stories-tab-bar>
            <stories-tab-button tab="actions">
              <stories-label color="primary">Actions</stories-label>
            </stories-tab-button>
            <stories-tab-button tab="controls">
              <stories-label color="primary">Controls</stories-label>
            </stories-tab-button>
          </stories-tab-bar>
          <stories-tab tab="actions">
            <stories-addon-actions></stories-addon-actions>
          </stories-tab>
          <stories-tab tab="controls">
            <stories-addon-controls></stories-addon-controls>
          </stories-tab>
        </stories-tabs>
      </stories-split-pane>
    </div>
  </stories-split-pane>
</stories-app>
